### ISSUE TITLE
Homeassistant 2024.8 "input properties are deprecated

### ISSUE THREAD

**Issue by Automot360** [sstratoti/actionable-notifications-subflow-for-ios#11]
Since Homeassistant 2024.8 service calls are renamed, NR delivers:
"The domain and service input properties are deprecated 
and will be removed in version 1.0. Please use the action property instead."

Hopefully you are able to update the subflow?

Thanks for your work.

**Comment by okets** [comment]
Where do you get this notification from?
I'm on latest version of home assistant, integrations and node-red plugins and all works fine for me.

**Comment by okets** [comment]
I can Confirm this bug.
I forked this subflow so It didn't appear right away for me.
this is also why I can't push my fix here.

the solution is very easy:
in the [create service call] node replace " msg.payload.domain" and " msg.payload.service" with a simple " msg.payload.action"

1) delete the domain from here:
msg.payload= {
...
    domain:"notify"
}
2) call the service like that:
services.trim().split(/,\s*/).forEach(service => {
    if(!service) return;
    msg.payload.action = `notify.${service}`;
    node.send(msg);
});

**Comment by sstratoti** [comment]
Thanks all for reporting this. I will take a look this week and push an update.

**Comment by sstratoti** [comment]
In addition to fixing this, I also cleaned up some of the code.

I'm alpha testing a new version of this at home for the next few days to make sure everything is still working, and then I'll push a new version up.

**Comment by marleyjaffe** [comment]
Can you share an updated version of the subflow with the necessary changes? Based on @okets comment, I believe I update:
```
services.trim().split(/,\s*/).forEach(service => {
    if(!service) return;
    msg.payload.service = service;
    node.send(msg);
});
```
 with:
```
services.trim().split(/,\s*/).forEach(service => {
    if(!service) return;
    msg.payload.action = notify.${service};
    node.send(msg);
});
```
however, I am unclear on the necessary changes to the domain part:
```
msg.payload = {
        domain: 'notify',
        data: {
            title: xTitle,
            message: xMessage,
            data: {
                push: {},
                tag: xTag
            }
        }
    };
```

Thank you!

**Comment by sstratoti** [comment]
Yes, I've just been alpha testing it this week. There were one or two issues with my updates, but it's been stable for a few days now.

I'll push it up this evening.

**Comment by marleyjaffe** [comment]
Great, thank you! I will be implementing this for the first time, I was using a different NR implementation of sending push notifications, but will provide any bugs or issues that I experience once you push the update.
