### ISSUE TITLE
nodered 3.1.0 debug warning

### ISSUE THREAD

**Issue by priit123** [sstratoti/actionable-notifications-subflow-for-ios#7]
"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."

**Comment by JB09** [comment]
Looks like an external fix is in the works: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/pull/1063

**Comment by priit123** [comment]
Running now Nodered 3.1.0 - Home Assistant add-on version 15.0.0 
It is fixed.

**Comment by sstratoti** [comment]
Sorry, just seeing this. Yeah, this was an issue with the node red palette, not with the subflow. Glad to hear you worked it out.
